### ISSUE TITLE
CLI doesn't compile on arm with nightly build >1.71.0 (7908a1d65 2023-04-17)

### ISSUE THREAD

**Issue by Keyruu** [Odonno/surrealdb-migrations#35]
The error produced is: 
```
error[E0275]: overflow evaluating the requirement `[closure@/Users/lro/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geo-0.24.1/src/algorithm/map_coords.rs:855:69: 855:72]: Fn<(geo_types::Coord<T>,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geo`)
  = note: required for `&[closure@map_coords.rs:855:69]` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: the full type name has been written to '/var/folders/vz/mcg3p00n099bxp3rdvjj6f5c0000gn/T/cargo-installUfxvvY/release/deps/geo-b2aff91d3d37fe24.long-type-17612579219348647092.txt'
  = note: 128 redundant requirements hidden
  = note: required for `&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...` to implement `Fn<(geo_types::Coord<T>,)>`
  = note: the full type name has been written to '/var/folders/vz/mcg3p00n099bxp3rdvjj6f5c0000gn/T/cargo-installUfxvvY/release/deps/geo-b2aff91d3d37fe24.long-type-4872500827442011049.txt'

For more information about this error, try `rustc --explain E0275`.
error: could not compile `geo` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `surrealdb-migrations v0.9.5`, intermediate artifacts can be found at `/var/folders/vz/mcg3p00n099bxp3rdvjj6f5c0000gn/T/cargo-installUfxvvY`
```

This is the related issue in the geo library https://github.com/georust/geo/issues/1010.
It is fixed in geo 0.25.0. 
For now I just use an earlier nightly version for it to work.

**Comment by Odonno** [comment]
Sorry I didn't respond to you earlier @Keyruu 

It seems to be the same error as #42 as cargo 1.71.0 is now generally available.

I think you had your answer but let's hope beta-10 is coming soon.

**Comment by Odonno** [comment]
With the release of 1.0.0, this issue should no longer occurs.

You can download the latest release of `surrealdb-migrations`: 

```
cargo install surrealdb-migrations@1.0.0-preview.1
```
